### ISSUE TITLE
column ordering - haybaler_taxonomy.py

### ISSUE THREAD

**Issue by colindaven** [MHH-RCUG/haybaler#38]
Hi @poer-sophia 

it would be great - having spoken with Jens too - to change the order of the columns in the `haybaler_taxonomy.py` output.

Specifically, the taxonomy should be inserted in the final columns, after the more important abundance values.

We currently have :
1_AP011540_1_Rothia_mucilaginosa_DY_18_DNA__complete_genome_BAC Rothia  Bacteria;Actinobacteria;Actinomycetia;Micrococcales;Micrococcaceae;Rothia;      2264603.0       59.62   0.0
     0.0     2142.86

But it is more readable if we add the columns 2 and 3 to the end of the column list/ df

 Rothia  Bacteria;Actinobacteria;Actinomycetia;Micrococcales;Micrococcaceae;Rothia;

What do you think ?

**Comment by poer-sophia** [comment]
Yes that makes sense

**Comment by colindaven** [comment]
done by Sophia
