### ISSUE TITLE
Option "all taxa" in prepare for R heatmaps

### ISSUE THREAD

**Issue by poer-sophia** [MHH-RCUG/haybaler#6]
Hey @colindaven, ich habe Donnerstag mit Joshua geredet und ihm gezeigt wie er die heatmaps mit den Skripten machen kann. Er meinte es wäre gut, wenn man auch auswählen kann, dass alle Organismen in die heatmap kommen und nicht nur 20/30/...

Ich hätte gesagt, ich bau entweder eine Option ein, die wc nutzt, so was in die Richtung:

number_of_taxa=$( wc -l $infile)

und man kommentier dann eine der beiden Optionen aus.
Oder ich schreibe einfach als Kommentar dazu, dass man number_of_taxa ganz hoch einstellen soll, z.B 10000 oder so, dann sollten ja auch alle Organismen genommen werden. 

Was meinst du?

**Comment by colindaven** [comment]
Hi Sophia, 

das Problem bleibt - wenn man mehr als ca 40-50 Taxa hat, verschwinden die Namen. Das ist Joshua sicherlich gar nicht mal bewusst.

Jedenfalls, man kann folgendes probieren

- Page Size in R so gross einstellen, dass man möglichst viele Taxa angucken kann
- Eingrenzung auf z.b 40 Taxa als Argument zulassen (im bash $1 wäre doch der erste Argument)
- Default werden alle Taxa geschrieben  -- > aber mit Warnung im Header Schift, solange die "Page size" Problem nicht geklärt ist

Einverstanden ?

**Comment by poer-sophia** [comment]
Ja klar, das klingt sinnvoll.

**Comment by poer-sophia** [comment]
@colindaven I tried to use a bigger pdf size to show more taxa. In general it worked, so to see double the amount of taxa you need double the size, otherwise it is impossible to read the lables of the row and columns. But then the names are very very little, so it is possible to see the clustering of a lot of data at once but when you want to know which organism is a specific row you need to zoom in. 

For the heatmaply heatmaps it is kind of similar but there are a few things which are better. First you dont need to arrange the size, automaticly all data with all lables is shown. Though without zooming, the lables of the taxa are overlapping so again it is not possible to see the whole heatmap and read the names of the organisms. But there are better possibilitys for zooming because you can zoom for just the rows, so than you  maybe just see 30 rows at the same time but you can still see all columns. And in that zoomed in state it is also possible to scroll through the data. 

I dont know if you know what I mean or how much you tried with the heatmaply heatmaps. But I would say for the heatmaply heatmaps  we could just take more data and everything is shown. For the base heatmaps it is also possible to show more data but it needs a little more work to implement and it is not possible to scroll or something like that,  just to zoom in. 

I tried this in my haybaler directory:
/working2/rcug_lw/sophias_projekte/haybaler
I used 200 taxa and arragend the size for the raw_heatmap, the sqarerooted hetamap has the default size. Maybe you want to take a look at the heatmaps.

**Comment by colindaven** [comment]
I couldn't find the heatmaps with 200 taxa in that folder, or the larger sizes (max 50, as usual..). They probably got overwritten ?

But thanks for this, it's good to know heatmaply is more dynamic. Did you show the various options to Ilona and Joshua too ?

**Comment by poer-sophia** [comment]
Oh yes maybe overwritten. I will reproduce them later. No I did´t show this to Ilona and Joshua yet but i am going to do this soon and write them an email.

**Comment by poer-sophia** [comment]
But the heatmaps are there. For example /working2/rcug_lw/sophias_projekte/haybaler/RPMM_haybaler.csv.filt.heatmap.csv_heatmap1_raw.pdf.
Or all of the heatmaply heatmaps. And they were never overwritten... at least I never reproduced them. 
I showed the heatmaply heatmaps with more taxa today to Ilona and Joshua and they said that it looks good. So with the heatmaply heatmaps it is possible to make heatmaps with more taxa and still be able to see everything.

**Comment by colindaven** [comment]
Ok, must have been mistaken, since I definitely copied and looked at different files. Yes, I think there are 67 species in the one heatmap and they look good. Thanks. I was actually expecting something even bigger, 80-100 + taxa.

I'm happy heatmaply is working out so well and was glad to see the new sqrt heatmaps in Ilona's  talk today in the  BT seminar.

**Comment by poer-sophia** [comment]
But there are more taxa in it. It should be 200... Maybe you just looked at the basic squareroot heatmap? Because that was kind of my negative control when I tried around with changing the pdf size. So I changed the size for the raw heatmap, but not the squarerooted one. That is why just a few more taxa are shown in the sqarerooted heatmap but by far not all. In the raw heatmap should be all species and in the heatmaply heatmaps too. 

If not then I dont know what goes wrong at this point. 

And yes the heatmaps from Ilona looked very good, thats really nice.

**Comment by colindaven** [comment]
Yep you're right, I was just looking at the sqrt one. My pdf software struggled to show it properly with the right zoom, and the cex. text size likely needs to be adjusted.
Still, it's an option you can include --all-taxa or whatever.

Possibly we should generate everything all the time - what do you think, to avoid being accused of hiding relevant data?

- subfolder top_50_taxa
- subfolder all_taxa

**Comment by poer-sophia** [comment]
Yes that sounds good

**Comment by poer-sophia** [comment]
Currently in the script prepare_for_R_heatmaps the original haybaler.csv with all taxa is shortened to a specific amount of taxa. So to get both, 50 and all taxa the script prepare_for_R_heatmaps and the R script itself need to run two times . And the prepare script would need to be edited to the wanted amount of taxa every time manually. 

So I thought it would be easier if I include an option in the R script how many taxa should be taken. Then I could execute the R script  two times in the runbatch_create_R_heatmaps script, one time with all taxa and the other time with 50 taxa.
What do you think?

**Comment by colindaven** [comment]
Yep, a bash script argument with no_taxa=$1 (1 = first argument) would be excellent, true.

**Comment by poer-sophia** [comment]
That would work too but I thought about a R argument because  otherwise I would need another bash script to start that bash script with two different values automatically  for the no_taxa argument.

**Comment by colindaven** [comment]
Would we ? It would feel a bit strange restricting the taxa a) in the bash script and b) in R

Why not create the method as a bash function (if you are worried about duplicating code) and call that function twice, eg with 50 and 100 taxa or whatever.

Another (better?) alternative: merge the prepare script and this one, to simplify things.

https://github.com/MHH-RCUG/haybaler/blob/main/runbatch_create_heatmap.sh

**Comment by poer-sophia** [comment]
Okay I guess I will merge the prepare and the runbatch_create_heatmaps function
