### ISSUE TITLE
runbatch_heatmaps.sh: line 107: syntax error near unexpected token `else'

### ISSUE THREAD

**Issue by colindaven** [MHH-RCUG/haybaler#62]
INFO: Script completed
runbatch_heatmaps.sh: line 107: syntax error near unexpected token `else'
runbatch_heatmaps.sh: line 107: `else'

**Comment by colindaven** [comment]
temp fix by commenting with . @poer-sophia TODO
https://github.com/MHH-RCUG/haybaler/commit/fde6a95932bd449b57f561882c0a8f44f9287fd5

**Comment by poer-sophia** [comment]
Should be fixed, it was just an "if" too many. It was like a double block of code, I think I copied that part one too many times and somehow didn't notice it.
