### ISSUE TITLE
Remove Haybaler output before rerunning haybaler

### ISSUE THREAD

**Issue by poer-sophia** [MHH-RCUG/haybaler#65]
@colindaven yesterday Ilona needed haybaler but she wanted different rpmm and readcount limit. So first she run postprocess and then she wanted to run haybaler again but with the adjusted limits. 

Because Haybaler always wants to add new samples to the existing haybaler csv files and the files with all samples already exist from the first run, nothing changes. 

So I guess it would make sense to delete the haybaler output files when starting run_haybaler.sh

**Comment by colindaven** [comment]
Ok, I'll take care of it. Thanks - I thought you were on holiday already? Enjoy it !

**Comment by poer-sophia** [comment]
not yet, monday and tuesdayI had seminar and until the end of the week I do homeoffice, so I can do this too.

**Comment by colindaven** [comment]
Ok, I'm still having quite a lot of problems testing the new env on the dev branch.

https://github.com/MHH-RCUG/Wochenende/issues/149
