### ISSUE TITLE
Copy heatmaps script ?

### ISSUE THREAD

**Issue by poer-sophia** [MHH-RCUG/haybaler#7]
@colindaven  Joshua hat mich gefragt ob es möglich ist die Heatmaps Scripts bei Wochenende automatisch mit zu kopieren oder sowas. Ich hätte überlegt, dass man die Heatmaps entweder  direkt in Wochenende_postprocess einbaut oder (damit man die Anzahl der taxa noch einstellen kann wen man will) zumindest im postprocess Skript den haybaler_output Ordner erstellt und die heatmaps Skripts darein kopiert.  Dann müsste man die Heatmaps Skripts nur noch laufen lassen und nicht mehr darüber nachdenken was von wo wohin kopiert werden muss.

**Comment by colindaven** [comment]
Ja, schick doch mal ein Pull Request bitte.

Ein Problem ist - Wochenende braucht R nicht. Ich lasse die Heatmap Skripts auf einem anderen R Server laufen. Aber wenn es scheitert ist auch nicht schlimm. Insofern - copy ja, laufen ja, wenn es scheitert muss man es nochmal probieren.

**Comment by colindaven** [comment]
Edit - @poer-sophia please write in English, if necessary just copy paste into google translate. This is a global site and all our docs are in English - thanks.

**Comment by poer-sophia** [comment]
Yes of course, should I edit this issue or is this just an information for the next time?

**Comment by poer-sophia** [comment]
@colindaven 

Joshua said it would be great if the heatmaps scripts could be copied in the output directory every time you run haybaler, not just in the postprocess script. So I edited the run_haybaler.sh script and now the scripts are copied from /mnt/ngsnfs/tools/dev/haybaler/.

If you would run the run_haybaler.sh script alone or in the postprocess script in both caese the heatmaps scripts would be copied in the haybaler_output directory. 

But I know that in the postprocess sript it is possible to change the directory where all the scripts are copied from, so if someone would set the haybaler_directory variable in the postprocess script to an different directory, it would not affect the heatmaps script so maybe in that case the heatmaps scripts could not be copied. 
So I made an option in the run_heatmas.sh script that if an argument is given, it takes that argument as the haybaler_directory. If not, it takes /mnt/ngsnfs/tools/dev/haybaler/ as deafult directory to copy the scripts from. 

In the postprocess script the haybaler_directory would be given as an argument to the run_haybaler.sh script. 
If the script is run alone you can just type  "bash run_haybaler.sh" and everything will work fine. 

Does this makes sense? I should probably push this  to dev so you can see what I mean, right?

**Comment by colindaven** [comment]
Ok, if he wants that. So he is running Haybaler repeatedly after the postprocess script? Interesting. As a standalone tool, this idea makes sense. This means haybaler also has to be the end of the pipeline (probably), or at least of this pipeline output section.

Yes, it could all get a bit complicated. Maybe we could set and use an environment variable of the locations of both Wochenende and haybaler as part of the installation instructions ? What do you think ?

eg only using hard coded variables if the HAYBALER_DIR and WOCHENENDE_DIR env variables are not set ( from postprocess.sh, line 31-33)

Yeah, pls push to dev.

**Comment by poer-sophia** [comment]
I have already pushed it. 

The enviroment variables sound good.
